import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Annie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`relative w-full min-h-screen antialiased bg-bg3 bg-cover bg-center bg-no-repeat bg-fixed text-primary overflow-y-auto xl:overflow-y-hidden`}
      >
        {/* <div className="absolute w-full h-full inset-0 bg-black/30 -z-10" /> */}
        {children}
      </body>
    </html>
  );
}
